[package]
name = "cargo-err-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-err-lib = { git = "https://github.com/jesseglick/cargo-err-lib", version = "0.1.0" }
